# nome = input ("DIgite seu nome: ")
# nascimento = input("Qual seu ano de nascimento? ")
# email = input("Digite seu email: ")
# print("Nome: ", nome , ". E-mail: " , email , ". Nascimento: ", nascimento)
# print(nome)
# print("Nascimento: ")
# print(nascimento)
# print("Email: ")
# print (email)
# num1 = input ("digite um número: ") 
# num2 = input ("digite um número: ") 
# num3 = input ("digite um número: ") 
# num4 = input ("digite um número: ")
# print("=> ", num1 , "=> ", num2, "=> ", num3, "=> ", num4)

a = int(input("Digite um número: "))
print (a + 5)

int(input("Texto"))
